name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
     
      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clean
        run: dotnet clean ./src/X509StoreFinder/X509StoreFinder.csproj -c $BUILD_CONFIG

      - name: Build
        run: dotnet clean ./src/X509StoreFinder/X509StoreFinder.csproj -c $BUILD_CONFIG

      - name: Pack X509StoreFinder
        run: dotnet pack ./src/X509StoreFinder/X509StoreFinder.csproj -c $BUILD_CONFIG --no-build --include-source --include-symbols -o ./artifacts
      
      - name: Setup nuget
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest

      - name: Push to MyGitHub
        env:
           GITHUB_NUGET_URL: https://nuget.pkg.github.com/dina-heidar/index.json
           GITHUB_NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push ./artifacts/X509StoreFinder.*.nupkg -k $GITHUB_NUGET_API_KEY -s $GITHUB_NUGET_URL --skip-duplicate
          
    