name: Releaser

on:
  push:
    tags:
    - '*.*.*'
jobs:
  build:
    env:
      BUILD_CONFIG: Release

    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
     
      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Install Dependencies
        run: dotnet restore

      - name: Clean
        run: dotnet clean ./src/X509StoreFinder/X509StoreFinder.csproj -c $BUILD_CONFIG

      - name: Build
        run: dotnet clean ./src/X509StoreFinder/X509StoreFinder.csproj -c $BUILD_CONFIG

      - name: Pack 
        run: dotnet pack ./src/X509StoreFinder/X509StoreFinder.csproj -c $BUILD_CONFIG --no-build --include-source --include-symbols -o ./artifacts
      
      - name: Setup nuget
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest

      - name: Push to NuGet
        env:
         NUGET_URL: https://api.nuget.org/v3/index.json
         NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/X509StoreFinder.*.nupkg -k $NUGET_API_KEY -s $NUGET_URL --skip-duplicate
     
